### ISSUE TITLE
Error running the scanner github action 

### ISSUE THREAD

**Issue by RaviVaranasi** [mitchspano/sfdx-scan-pull-request#66] opened 2023-11-10 04:26 UTC
Below is the error running the Github action. We did not change anything in the action.  Did a transitive dependency change. The error indicates we did not get a JSON payload back

```
{
  message: 'Unexpected token T in JSON at position 1',
  status: undefined,
  stack: 'SyntaxError: Unexpected token T in JSON at position 1\n' +
    '    at JSON.parse (<anonymous>)\n' +
    '    at /home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:12983\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:12738\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at o (/home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:12485)\n' +
    '    at cli (/home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:12871)\n' +
    '    at /home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:13250\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:12738',
  output: undefined
}
```

```

      - name: Run SFDX Scanner - Report findings as comments
        uses: mitchspano/sfdx-scan-pull-request@v0.1.15
        with:
          pmdconfig: ruleset.xml
          severity-threshold: 3
          strictly-enforced-rules: '[{ "engine": "pmd", "category": "Performance", "rule": "AvoidDebugStatements" }]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by mitchspano** [comment] 2023-11-16 23:35
Are you able to reproduce this issue? I am using v0.1.15 with no issues

<img width="1023" alt="image" src="https://github.com/mitchspano/sfdx-scan-pull-request/assets/18402464/c735ceee-5efd-4e7a-95e2-5187289dc59a">
<img width="937" alt="image" src="https://github.com/mitchspano/sfdx-scan-pull-request/assets/18402464/3a86055d-6318-4fc5-b645-3d40673c870f">
<img width="936" alt="image" src="https://github.com/mitchspano/sfdx-scan-pull-request/assets/18402464/02af1082-46ff-48e2-87d8-4b8e1169e55e">

**Comment by mitchspano** [comment] 2024-01-13 20:04
closing due to inaction and inability to reproduce

**Closed by mitchspano** 2024-01-13 20:04 UTC
